Edit setting post type register
wpmetabox/mb-custom-post-type pull request #59
Opened 2023-11-02 07:45 UTC by lexuanbao161096

2023-11-07 12:06 UTC, rilwis requested changes
Em format code nữa nhé.

2023-11-07 12:06 UTC, rilwis commented on src/EditSettingRegister.php
> +			.edit-mb-post-type, .edit-mb-taxonomy{
Để chung 1 class đi em, cho dễ hiểu. VD: `mbcpt-register-outside`

2023-11-08 01:54 UTC, lexuanbao161096 commented on src/EditSettingRegister.php
> +		add_action( 'admin_head', [ $this, 'add_css_post_type' ] );
Do pre_get_posts kích hoạt trước khi get_current_screen() được định nghĩa nên ko dùng được hàm get_current_screen() mà phải dùng $pagenow anh ạ

2023-11-08 02:01 UTC, lexuanbao161096 commented on src/EditSettingRegister.php
> +			$value              = json_decode( json_encode( $post_type ), true );
Chỗ này em convert object thành mảng cho dễ xử lý thôi ạ

2023-11-08 16:40 UTC, rilwis commented on src/EditSettingRegister.php
> +		add_action( 'admin_head', [ $this, 'add_css_post_type' ] );
Thế thì check cẩn thận ở front end xem có bị gì ko. Code ntn khá nguy hiểm vì sẽ chạy ở mọi chỗ, và a thấy rất có khả năng bị lỗi tiềm tàng nào đó. E cứ thử check lại với các hook trong admin như `is_admin()` hoặc `admin_init` xem ntn, vì thực chất tất cả các đoạn này chỉ cần chạy ở đúng 1 trang.

2023-11-08 16:42 UTC, rilwis requested changes

2023-11-08 16:42 UTC, rilwis commented on src/EditSettingRegister.php
> +			$value              = json_decode( json_encode( $post_type ), true );
Vậy thì ép kiểu `$array = (array) $object;` hoặc `$array = get_object_vars($object);`

2023-11-09 07:55 UTC, lexuanbao161096 commented on src/EditSettingRegister.php
> +		add_action( 'admin_head', [ $this, 'add_css_post_type' ] );
class `EditSettingRegister` nó chỉ khởi chạy khi là is_admin rồi mà anh.

2023-11-14 12:14 UTC, merged