A link to create a field group after a CPT has been created.
wpmetabox/mb-custom-post-type pull request #70
Opened 2024-07-10 08:30 UTC by lexuanbao161096

2024-07-11 08:03 UTC, rilwis requested changes

2024-07-11 08:03 UTC, rilwis commented on src/Edit.php
> +		$link_field = admin_url( 'post-new.php?post_type=meta-box&post_title=' . get_the_title(). ' Fields' );
Dùng `sprintf` cho `get_the_title() . ' Fields'` nhé.

2024-07-11 08:05 UTC, rilwis requested changes

2024-07-11 08:05 UTC, rilwis commented on src/Edit.php
> +			'linkPostType'  => ( defined( 'MBB_VER' ) && $settings ) ? $link_field . '&mb-post-type=' . $settings['slug'] : '',
Chỗ này có truyền tham số như của taxonomy được ko?

2024-07-12 01:35 UTC, lexuanbao161096 commented on src/Edit.php
> +			'linkPostType'  => ( defined( 'MBB_VER' ) && $settings ) ? $link_field . '&mb-post-type=' . $settings['slug'] : '',
Không được anh ạ do bên builder post type nó xử lý khác nên nó ko nhận default value như taxonomy được ạ

2024-07-17 05:16 UTC, rilwis approved these changes

2024-07-17 05:16 UTC, merged